data_dict = {
    "Netz_Wirkleistung": {
        "Col_Name": "Netz_Wirkleistung",
        "Name": "Power drawn from the grid",
        "Unit": "[W]",
        "Label": "Power drawn from the grid in [W]"
    },
    "PV_Wirkleistung": {
        "Col_Name": "PV_Wirkleistung",
        "Name": "Power generated by the PV",
        "Unit": "[W]",
        "Label": "Power generated by the PV in [W]"
    },
    "Last_Rechenwert": {
        "Col_Name": "Last_Rechenwert",
        "Name": "Total power usage",
        "Unit": "[W]",
        "Label": "Total power usage [W]"
    },
    "Niederschlag": {
        "Col_Name": "Niederschlag",
        "Name": "Precipitation",
        "Unit": "[mm/min]",
        "Label": "Precipitation in [mm/min]"
    },
    "Temperatur": {
        "Col_Name": "Temperatur",
        "Name": "Temperature",
        "Unit": "[°C]",
        "Label": "Temperature in [°C]"
    },
    "rel_Feuchte": {
        "Col_Name": "rel_Feuchte",
        "Name": "relative Humidity",
        "Unit": "[%]",
        "Label": "Relative Humidity in [%]"
    },
    "Windgeschwindigkeit": {
        "Col_Name": "Windgeschwindigkeit",
        "Name": "Wind velocity",
        "Unit": "[m/s]",
        "Label": "Wind volicity in [m/s]"
    },
    "Windrichtung": {
        "Col_Name": "Windrichtung",
        "Name": "wind direction",
        "Unit": "[deg]",
        "Label": "Wind direction in [deg]"
    },
    "Luftdruck": {
        "Col_Name": "Luftdruck",
        "Name": "Air Pressure",
        "Unit": "[hPa]",
        "Label": "Air pressure in [hPa]"
    }
}
